"""Initial migration - account, holdings, transactions

Revision ID: df140d6da73f
Revises: 
Create Date: 2026-04-28 16:58:34.861741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df140d6da73f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cash_balance', sa.DECIMAL(precision=19, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crypto_holdings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=19, scale=8), nullable=False),
    sa.Column('avg_cost_basis', sa.DECIMAL(precision=19, scale=4), nullable=False),
    sa.Column('total_invested', sa.DECIMAL(precision=19, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_holdings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=19, scale=8), nullable=False),
    sa.Column('avg_cost_basis', sa.DECIMAL(precision=19, scale=4), nullable=False),
    sa.Column('total_invested', sa.DECIMAL(precision=19, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('asset_type', sa.String(length=10), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.DECIMAL(precision=19, scale=8), nullable=False),
    sa.Column('price_per_unit', sa.DECIMAL(precision=19, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('exchange_rate', sa.DECIMAL(precision=19, scale=8), nullable=False),
    sa.Column('usd_price_per_unit', sa.DECIMAL(precision=19, scale=4), nullable=False),
    sa.Column('total_usd_value', sa.DECIMAL(precision=19, scale=4), nullable=False),
    sa.Column('fees', sa.DECIMAL(precision=19, scale=4), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('stock_holdings')
    op.drop_table('crypto_holdings')
    op.drop_table('accounts')
    # ### end Alembic commands ###
